name: Test & Upload Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clear Node Modules Cache (if needed)
        run: rm -rf node_modules

      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: CD to client directory
        run: cd client

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npx vitest run --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Thian0509/Monkey-RiverTeam11
